version: '2'

networks:
  test.local:

services:
  tier1a:
    build: tier1a/
    ports:
        - "127.0.0.3:60080:80"
        - "127.0.0.3:60443:443"
    environment:
        - PREFIX=tier1a
    volumes:
        - .:/scenario:ro
        - ../../../:/thruk:ro
    networks:
      test.local:
        aliases:
          - tier1a.test.local
    hostname: tier1a
    domainname: test.local

  tier1b:
    build: tier1b/
    ports:
        - "127.0.0.3:60081:80"
        - "127.0.0.3:60444:443"
    environment:
        - PREFIX=tier1b
    volumes:
        - .:/scenario:ro
    networks:
      test.local:
        aliases:
          - tier1b.test.local
    hostname: tier1b
    domainname: test.local

  tier1c:
    build: tier1c/
    ports:
        - "127.0.0.3:60082:80"
        - "127.0.0.3:60445:443"
    environment:
        - PREFIX=tier1c
    volumes:
        - .:/scenario:ro
    networks:
      test.local:
        aliases:
          - tier1c.test.local
    hostname: tier1c
    domainname: test.local

  tier1d:
    build: tier1d/
    ports:
        - "127.0.0.3:60083:80"
        - "127.0.0.3:60446:443"
    environment:
        - PREFIX=tier1d
    volumes:
        - .:/scenario:ro
        - ../../../:/thruk:ro
    networks:
      test.local:
        aliases:
          - tier1d.test.local
    hostname: tier1d
    domainname: test.local


  tier2a:
    build: tier2a/
    environment:
        - PREFIX=tier2a
    volumes:
        - .:/scenario:ro
        - ../../../:/thruk:ro
    networks:
      test.local:
        aliases:
          - tier2a.test.local
    hostname: tier2a
    domainname: test.local

  tier2b:
    build: tier2b/
    environment:
        - PREFIX=tier2b
    volumes:
        - .:/scenario:ro
    networks:
      test.local:
        aliases:
          - tier2b.test.local
    hostname: tier2b
    domainname: test.local

  tier2c:
    build: tier2c/
    environment:
        - PREFIX=tier2c
    volumes:
        - .:/scenario:ro
        - ../../../:/thruk:ro
    networks:
      test.local:
        aliases:
          - tier2c.test.local
    hostname: tier2c
    domainname: test.local

  tier2d:
    build: tier2d/
    environment:
        - PREFIX=tier2d
    volumes:
        - .:/scenario:ro
    networks:
      test.local:
        aliases:
          - tier2d.test.local
    hostname: tier2d
    domainname: test.local

  tier3a:
    build: tier3a/
    environment:
        - PREFIX=tier3a
    volumes:
        - .:/scenario:ro
        - ../../../:/thruk:ro
    networks:
      test.local:
        aliases:
          - tier3a.test.local
    hostname: tier3a
    domainname: test.local

  tier3b:
    build: tier3b/
    environment:
        - PREFIX=tier3b
    volumes:
        - .:/scenario:ro
        - ../../../:/thruk:ro
    networks:
      test.local:
        aliases:
          - tier3b.test.local
    hostname: tier3b
    domainname: test.local

#  krb5:
#    build: krb5/
#    volumes:
#        - /dev/urandom:/dev/random:ro
#    networks:
#      test.local:
#        aliases:
#          - krb5.test.local
#    hostname: krb5
#    domainname: test.local
