port: 4444
logger: Console
engines:
  logger:
    Console:
      log_level: debug
plugins:
  "OAuth2::Server":
    state_required: 1
    clients:
      clientö:
        client_secret: secret
        scopes:
          openid: 1
          profile: "profile"
          email: "email@öäüß€"
      omdadmin:
        client_secret: secret
        scopes:
          openid: 2
          profile: "profile"
          email: "omdadmin@localhost"
      omdadmin:
        client_secret: secret
        scopes:
          openid: 3
          profile: "profile"
          email: "testuser@localhost"
