version: "2"

services:
  omd:
    build: omd/
    ports:
        - "127.0.0.3:60080:80"
    environment:
        - TZ=Europe/Berlin
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - ../../../:/thruk:ro
  arachni:
    build: arachni/
    ports:
      - "9292:9292"
    volumes:
        - .:/test:ro
        - ./results:/work:rw
    command: bin/arachni_web -o 0.0.0.0
