---
- hosts: all
  roles:
    - role: common
    - role: local_tests
    - role: thruk_developer
  tasks:
  - name: "omd config change"
    shell: "omd config demo change"
    args:
      stdin: |
        APACHE_MODE=own
        PNP4NAGIOS=off
        LIVESTATUS_TCP=on
  - name: copy naemon example.cfg
    copy:
      src: /omd/sites/demo/share/doc/naemon/example.cfg
      dest: /omd/sites/demo/etc/naemon/conf.d/example.cfg
      owner: demo
      group: demo
  - name: Increase default load limit
    replace:
      path: /omd/sites/demo/etc/naemon/conf.d/example.cfg
      regexp: '(check_local_load\!5,5,5\!10,10,10)'
      replace: 'check_local_load!99,99,99!99,99,99'
  - name: copy naemon test.cfg
    copy:
      src: /root/test.cfg
      dest: /omd/sites/demo/etc/naemon/conf.d/test.cfg
      owner: demo
      group: demo
  - name: copy naemon testuser.cfg
    copy:
      src: /root/testuser.cfg
      dest: /omd/sites/demo/etc/naemon/conf.d/testuser.cfg
      owner: demo
      group: demo
  - lineinfile:
      path: /omd/sites/demo/etc/thruk/cgi.cfg
      regexp: '^authorized_contactgroup_for_admin='
      line: 'authorized_contactgroup_for_admin=testgroup'
  - lineinfile:
      path: /omd/sites/demo/etc/thruk/cgi.cfg
      regexp: '^authorized_contactgroup_for_configuration_information='
      line: 'authorized_contactgroup_for_configuration_information=testgroup2'
  - lineinfile:
      path: /omd/sites/demo/etc/thruk/cgi.cfg
      regexp: '^authorized_contactgroup_for_all_services='
      line: 'authorized_contactgroup_for_all_services=testgroup2'
  - lineinfile:
      path: /omd/sites/demo/etc/thruk/cgi.cfg
      regexp: '^authorized_contactgroup_for_all_hosts='
      line: 'authorized_contactgroup_for_all_hosts=testgroup2'
  - lineinfile:
      path: /omd/sites/demo/etc/thruk/cgi.cfg
      regexp: '^authorized_contactgroup_for_all_service_commands='
      line: 'authorized_contactgroup_for_all_service_commands=testgroup2'
  - lineinfile:
      path: /omd/sites/demo/etc/thruk/cgi.cfg
      regexp: '^authorized_contactgroup_for_all_host_commands='
      line: 'authorized_contactgroup_for_all_host_commands=testgroup2'
  - lineinfile:
      path: /omd/sites/demo/etc/htpasswd
      regexp: '^testuser:'
      line: 'testuser:$apr1$rYJHrFjl$CXBAGzkW1.dklpbNZ2rKu/'
  - lineinfile:
      path: /omd/sites/demo/etc/htpasswd
      regexp: '^testuser2:'
      line: 'testuser2:$apr1$XCZk.pKm$sN8YtngAPWNvNU1DLJci9/'
  - shell: echo "testkey" > /omd/sites/demo/var/thruk/secret.key
  - file:
      path: /omd/sites/demo/var/thruk/secret.key
      mode: 0600
      owner: demo
      group: demo
  - copy:
      src: /root/1.rpt
      dest: /omd/sites/demo/var/thruk/reports/
      owner: demo
      group: demo
  - copy:
      src: /root/1.tab
      dest: /omd/sites/demo/etc/thruk/panorama/
      owner: demo
      group: demo
  - copy:
      src: /root/1.tsk
      dest: /omd/sites/demo/var/thruk/downtimes/
      owner: demo
      group: demo
  - name: add example business process
    copy:
      src: /root/1.tbp
      dest: /omd/sites/demo/etc/thruk/bp/1.tbp
      owner: demo
      group: demo
