version: '2'

services:
  omd:
    build: omd/
    ports:
        - "127.0.0.3:60080:80"
        - "127.0.0.3:60443:443"
        - "127.0.0.3:60557:6557"
        - "127.0.0.3:61000:7000"
    environment:
        - TZ=Europe/Berlin
        - PREFIX=omd
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - ../../../:/thruk:ro
        - .:/scenario:ro
#  slow:
#    build: omd/
#    ports:
#        - "127.0.0.3:60081:80"
#        - "127.0.0.3:60444:443"
#        - "127.0.0.3:60558:6557"
#        - "127.0.0.3:61001:7000"
#    environment:
#        - TZ=Europe/Berlin
#        - PREFIX=slow
#    volumes:
#        - /etc/localtime:/etc/localtime:ro
#        - ../../../:/thruk:ro
#        - .:/scenario:ro
