version: '3.4'

networks:
  default:
    ipam:
     config:
       - subnet: 192.168.105.0/24

services:
  omd:
    build: omd/
    ports:
        - "127.0.0.3:60080:80"     # apache
        - "127.0.0.3:60557:6557"   # livestatus
        - "127.0.0.3:8003:8003"    # grafana
        - "127.0.0.3:4444:4444"    # oauth server
    volumes:
        - ../../../:/thruk:ro
        - .:/scenario:ro
    networks:
      default:
        ipv4_address: 192.168.105.2
